# Mirror of 10-pipa.conf — some images had a locally edited 20-pipa.conf
[Unit]
Wants=
Requires=setup-configfs.service
After=local-fs.target dbus.socket sys-kernel-config.mount setup-configfs.service systemd-modules-load.service
After=multi-user.target

[Service]
Environment=USB_MODED_ARGS=-r
ExecStartPre=
ExecStartPre=/bin/sh -c 'echo "" > /sys/kernel/config/usb_gadget/g1/UDC 2>/dev/null || true'
ExecStartPre=/bin/sh -c 'test -e /sys/kernel/config/usb_gadget/g1/UDC || /usr/bin/droid/setup-configfs.sh'
TimeoutStartSec=30
