[Service]
# Stock Sailfish connman unit passes --noplugin=wifi (hybris leftover).
# Mainline pipa needs the wifi plugin.
ExecStart=
ExecStart=/usr/sbin/connmand -n -W nl80211 --nobacktrace $SYSCONF_ARGS $CONNMAN_ARGS
